### ISSUE TITLE
merge Volto in fontTools.voltLib?

### ISSUE THREAD

**Issue by anthrotype** [TiroTypeworks/TiroTools#2]
Hi,

thank you for open-sourcing this work! I believe many foundries would find this quite useful.
I haven't used it or looked at the code yet, but I was wondering if you would be interested in merging your volt-to-fea converter into the upstream fonttools library?
I guess this could become a submodule of fontTools.voltLib (e.g. fontTools.voltLib.converter or similar).
Anyway, this is just a thought. It doesn't have to go into fonttools. But that could make the code a bit more easily/widely available in all applications that already depend on fonttools.

(Err I'm not volunteering to maintain this code :grimacing:. Khaled is already a regular FontTools contributor, if he likes he could continue work on that over there.)

**Comment by tiroj** [comment]
I'll discuss this with Khaled, to better understand the benefits and when he thinks it would make sense to do this. At the moment, I'm thinking of this very much as beta, which I've barely tested myself. It's something that came about during a project for a client who needed .fea sources for fonts we'd built using VOLT.

Ultimately, I'd like to build out the tool to also be able to convert .fea to .vtp, since we're occasionally making complex script additions to existing fonts with .fea sources, and my preference remains to work in VOLT.

**Comment by khaledhosny** [comment]
No objection in general, but on the technical side we would need to support Python 2 first (I have no interest in doing this, personally) or wait for FontTools to finally drop Python 2 support.

**Comment by anthrotype** [comment]
The latter would be preferable. As for the py3 only transition, we missed the proposed  1 Jan 2109 deadline, but I hope I can work on that before the end of this month.

**Comment by tiroj** [comment]
Doing some housekeeping. What's the status on this issue, and on FontTools py3 support?

**Comment by khaledhosny** [comment]
FontTools is Python 3-only already, I guess we can move it then.

**Comment by tiroj** [comment]
Ping.

Is this issue resolved?

**Comment by khaledhosny** [comment]
No, not yet.

**Comment by tiroj** [comment]
Any movement on this?

**Comment by khaledhosny** [comment]
I’ll work on it.

**Comment by khaledhosny** [comment]
Submitted a FontTools PR: https://github.com/fonttools/fonttools/pull/3164

**Comment by khaledhosny** [comment]
FontTools pull request is merged.
